//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FinalEntities : DbContext
    {
        public FinalEntities()
            : base("name=FinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accion> Accion { get; set; }
        public virtual DbSet<AgenteFitosanitario> AgenteFitosanitario { get; set; }
        public virtual DbSet<Agroquimico> Agroquimico { get; set; }
        public virtual DbSet<CampoFinca> CampoFinca { get; set; }
        public virtual DbSet<Perfil> Perfil { get; set; }
        public virtual DbSet<PerfilAccion> PerfilAccion { get; set; }
        public virtual DbSet<Productor> Productor { get; set; }
        public virtual DbSet<RecetaAgroquimica> RecetaAgroquimica { get; set; }
        public virtual DbSet<RecetaAgroquimicaDetalle> RecetaAgroquimicaDetalle { get; set; }
        public virtual DbSet<Solicitud> Solicitud { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<UsuarioPerfil> UsuarioPerfil { get; set; }
        public virtual DbSet<Vendedor> Vendedor { get; set; }
    }
}
