//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilAccion
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int IdPerfil { get; set; }
        public int IdAccion { get; set; }
    
        public virtual Accion Accion { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
