//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerfilAccion
    {
        public int IdPerfilAccion { get; set; }
        public string Nombre { get; set; }
        public int IdPerfil { get; set; }
        public int IdAccion { get; set; }
    
        public virtual Accion Accion { get; set; }
        public virtual Perfil Perfil { get; set; }
    }
}
