//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaAgroquimicaDetalle
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public int IdRecetaAgroquimica { get; set; }
        public int IdAgroquimico { get; set; }
    
        public virtual Agroquimico Agroquimico { get; set; }
        public virtual RecetaAgroquimica RecetaAgroquimica { get; set; }
    }
}
