//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaAgroquimicaDetalle
    {
        public int Id { get; set; }
        public int Cantidad { get; set; }
        public int IdRecetaAgroquimica { get; set; }
        public int IdAgroquimico { get; set; }
    
        public virtual Agroquimico Agroquimico { get; set; }
        public virtual RecetaAgroquimica RecetaAgroquimica { get; set; }
    }
}
