//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaAgroquimica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecetaAgroquimica()
        {
            this.RecetaAgroquimicaDetalle = new HashSet<RecetaAgroquimicaDetalle>();
        }
    
        public int Id { get; set; }
        public System.DateTime FechaReceta { get; set; }
        public string Diagnostico { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Entregado { get; set; }
        public int IdCampoFinca { get; set; }
        public int IdProductor { get; set; }
        public int IdAgenteFitosanitario { get; set; }
        public int IdVendedor { get; set; }
    
        public virtual AgenteFitosanitario AgenteFitosanitario { get; set; }
        public virtual CampoFinca CampoFinca { get; set; }
        public virtual Productor Productor { get; set; }
        public virtual Vendedor Vendedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecetaAgroquimicaDetalle> RecetaAgroquimicaDetalle { get; set; }
    }
}
