//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trabajo_Final_L4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdProductor { get; set; }
        public int IdCampoFinca { get; set; }
        public int IdAgenteFitosanitario { get; set; }
        public string Estado { get; set; }
    
        public virtual AgenteFitosanitario AgenteFitosanitario { get; set; }
        public virtual CampoFinca CampoFinca { get; set; }
        public virtual Productor Productor { get; set; }
    }
}
